"""
Core data structures and database schemas for the Quaero RAG engine.
"""

from typing import List, Optional, TYPE_CHECKING
from pydantic import Field
from lancedb.pydantic import Vector, LanceModel

from quaero.core.config import QUAERO_EMBEDDING_DIMENSIONS

# #HACK: Bypass Pylance's 'reportInvalidTypeForm' error.
# We give Pylance a dummy List[float] for static analysis, but feed 
# LanceDB the actual runtime Vector schema compiler in the else block.
if TYPE_CHECKING:
    EmbeddingVector = List[float]
else:
    from lancedb.pydantic import Vector
    from quaero.core.config import QUAERO_EMBEDDING_DIMENSIONS
    EmbeddingVector = Vector(QUAERO_EMBEDDING_DIMENSIONS)

class FileRecord(LanceModel):
    """
    Represents an ingested file tracked by the system.
    Used for change detection, source referencing, and cleanup.
    """
    file_id: str = Field(..., description="SHA-256 hash of the absolute file path. Acts as the primary key.")
    content_hash: str = Field(..., description="SHA-256 hash of the file content for change detection.")
    file_name: str = Field(..., description="The base name of the file (e.g., 'notes.txt')")
    absolute_path: str = Field(..., description="The absolute path to the file on the local disk")
    file_size_bytes: int = Field(..., description="File size in bytes")
    last_modified: float = Field(..., description="OS sub-second modification epoch timestamp")
    indexed_at: float = Field(..., description="Epoch timestamp when this file was added to the DB")


class ChunkRecord(LanceModel):
    """
    Represents an individual chunk of text extracted from a file.
    This maps directly to your LanceDB vector table.
    """
    chunk_id: str = Field(..., description="Unique ID for this chunk (e.g., '{file_id}_c{index}')")
    file_id: str = Field(..., description="Foreign key mapping this chunk back to its parent FileRecord")
    text_content: str = Field(..., description="The raw textual content of this chunk passed to the LLM")
    chunk_index: int = Field(..., description="The zero-indexed position of this chunk inside the original file")
    
    # LanceDB will automatically detect this field to store vector embeddings
    vector: Optional[EmbeddingVector] = Field(
        default=None,
        description="The high-dimensional embedding array generated by the embedding model"
    )